services:
  postgres:
    image: postgres:13
    container_name: poc1-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    volumes:
      - ./postgres/postgres_data:/var/lib/postgresql/data
      - ./postgres/scripts/init:/docker-entrypoint-initdb.d/
      - ./postgres/scripts:/postgres/scripts
    ports:
      - "2024:5432"

  worker:
    depends_on:
        - postgres
    image: poc1-worker
    container_name: poc1-worker
    env_file:
      - docker.env
    volumes:
      - ./emprego:/src

  duckdb:
    depends_on:
      - postgres
    image: poc1-duckdb
    container_name: poc1-duckdb
    env_file:
      - docker.env
    volumes:
      - ./emprego/db:/src
      - ./postgres:/src/postgres