companies = [
    "TecBrasil Soluções", "AlphaTech Inovações", "Bravo Engenharia", "Delta Construções", "Echo Telecomunicações",
    "Foxtrot Tecnologia", "GolfSoft", "Hotel Systems", "IndiaSoft", "Juliett Inovações", "Kilo Consultoria",
    "Lima Construções", "Mike Automação", "November InfoTech", "Oscar Networks", "Papa Segurança", "Quebec Serviços",
    "Romeu Engenharia", "Sierra Soluções", "Tango Transporte", "Uniforme Tecnologia", "Victor Telecom",
    "Whiskey Sistemas", "X-ray Inovações", "Yankee Consultoria", "Zulu Construções", "Alfa Segurança", "Bravo InfoTech",
    "Charlie Consultoria", "Delta Serviços", "Echo Engenharia", "Foxtrot Soluções", "Golf InfoTech", "Hotel Engenharia",
    "India Segurança", "Juliett Consultoria", "Kilo Serviços", "Lima Tecnologia", "Mike Inovações", "November Sistemas",
    "Oscar Consultoria", "Papa Construções", "Quebec InfoTech", "Romeu Soluções", "Sierra Serviços", "Tango Engenharia",
    "Uniforme Soluções", "Victor Consultoria", "Whiskey Segurança", "X-ray Tecnologia", "Yankee Inovações", "Zulu Serviços",
    "Alfa Construções", "Bravo Segurança", "Charlie Engenharia", "Delta InfoTech", "Echo Consultoria", "Foxtrot Serviços",
    "Golf Segurança", "Hotel Consultoria", "India Serviços", "Juliett Tecnologia", "Kilo Inovações", "Lima Sistemas",
    "Mike Consultoria", "November Construções", "Oscar InfoTech", "Papa Soluções", "Quebec Serviços", "Romeu Engenharia",
    "Sierra Soluções", "Tango Segurança", "Uniforme Tecnologia", "Victor Inovações", "Whiskey Consultoria", "X-ray Serviços",
    "Yankee Construções", "Zulu Segurança", "Alfa InfoTech", "Bravo Consultoria", "Charlie Serviços", "Delta Engenharia",
    "Echo Soluções", "Foxtrot Segurança", "Golf Consultoria", "Hotel Serviços", "India Tecnologia", "Juliett Inovações",
    "Kilo Sistemas", "Lima Consultoria", "Mike Construções", "November InfoTech", "Oscar Soluções", "Papa Segurança",
    "Quebec Serviços", "Romeu Engenharia", "Sierra Soluções", "Tango Tecnologia", "Uniforme Segurança", "Victor Consultoria",
    "Whiskey Serviços", "X-ray Construções", "Yankee InfoTech", "Zulu Consultoria", "Alfa Serviços", "Bravo Engenharia",
    "Charlie Soluções", "Delta Segurança", "Echo Consultoria", "Foxtrot Serviços", "Golf Engenharia", "Hotel Soluções",
    "India Segurança", "Juliett Consultoria", "Kilo Serviços", "Lima Tecnologia", "Mike Inovações", "November Sistemas",
    "Oscar Consultoria", "Papa Construções", "Quebec InfoTech", "Romeu Soluções", "Sierra Serviços", "Tango Engenharia",
    "Uniforme Soluções", "Victor Consultoria", "Whiskey Segurança", "X-ray Tecnologia", "Yankee Inovações", "Zulu Serviços",
    "Alfa Construções", "Bravo Segurança", "Charlie Engenharia", "Delta InfoTech", "Echo Consultoria", "Foxtrot Serviços",
    "Golf Segurança", "Hotel Consultoria", "India Serviços", "Juliett Tecnologia", "Kilo Inovações", "Lima Sistemas",
    "Mike Consultoria", "November Construções", "Oscar InfoTech", "Papa Soluções", "Quebec Serviços", "Romeu Engenharia",
    "Sierra Soluções", "Tango Segurança", "Uniforme Tecnologia", "Victor Inovações", "Whiskey Consultoria", "X-ray Serviços",
    "Yankee Construções", "Zulu Segurança", "Alfa InfoTech", "Bravo Consultoria", "Charlie Serviços", "Delta Engenharia",
    "Echo Soluções", "Foxtrot Segurança", "Golf Consultoria", "Hotel Serviços", "India Tecnologia", "Juliett Inovações",
    "Kilo Sistemas", "Lima Consultoria", "Mike Construções", "November InfoTech", "Oscar Soluções", "Papa Segurança",
    "Quebec Serviços", "Romeu Engenharia", "Sierra Soluções", "Tango Tecnologia", "Uniforme Segurança", "Victor Consultoria",
    "Whiskey Serviços", "X-ray Construções", "Yankee InfoTech", "Zulu Consultoria", "Alfa Serviços", "Bravo Engenharia",
    "Charlie Soluções", "Delta Segurança", "Echo Consultoria", "Foxtrot Serviços", "Golf Engenharia", "Hotel Soluções",
    "India Segurança", "Juliett Consultoria", "Kilo Serviços", "Lima Tecnologia", "Mike Inovações", "November Sistemas",
    "Oscar Consultoria", "Papa Construções", "Quebec InfoTech", "Romeu Soluções", "Sierra Serviços", "Tango Engenharia",
    "Uniforme Soluções", "Victor Consultoria", "Whiskey Segurança", "X-ray Tecnologia", "Yankee Inovações", "Zulu Serviços",
    "Alfa Construções", "Bravo Segurança", "Charlie Engenharia", "Delta InfoTech", "Echo Consultoria", "Foxtrot Serviços",
    "Golf Segurança", "Hotel Consultoria", "India Serviços", "Juliett Tecnologia", "Kilo Inovações", "Lima Sistemas",
    "Mike Consultoria", "November Construções", "Oscar InfoTech", "Papa Soluções", "Quebec Serviços", "Romeu Engenharia",
    "Sierra Soluções", "Tango Segurança", "Uniforme Tecnologia", "Victor Inovações", "Whiskey Consultoria", "X-ray Serviços",
    "Yankee Construções", "Zulu Segurança", "Alfa InfoTech", "Bravo Consultoria", "Charlie Serviços", "Delta Engenharia",
    "Echo Soluções", "Foxtrot Segurança", "Golf Consultoria", "Hotel Serviços", "India Tecnologia", "Juliett Inovações",
    "Kilo Sistemas", "Lima Consultoria", "Mike Construções", "November InfoTech", "Oscar Soluções", "Papa Segurança",
    "Quebec Serviços", "Romeu Engenharia", "Sierra Soluções", "Tango Tecnologia", "Uniforme Segurança", "Victor Consultoria",
    "Whiskey Serviços", "X-ray Construções", "Yankee InfoTech", "Zulu Consultoria", "Alfa Serviços", "Bravo Engenharia",
    "Charlie Soluções", "Delta Segurança", "Echo Consultoria", "Foxtrot Serviços", "Golf Engenharia", "Hotel Soluções",
    "India Segurança", "Juliett Consultoria", "Kilo Serviços", "Lima Tecnologia", "Mike Inovações", "November Sistemas",
    "Oscar Consultoria", "Papa Construções", "Quebec InfoTech", "Romeu Soluções", "Sierra Serviços", "Tango Engenharia",
    "Uniforme Soluções", "Victor Consultoria", "Whiskey Segurança", "X-ray Tecnologia", "Yankee Inovações", "Zulu Serviços",
    "Alfa Construções", "Bravo Segurança", "Charlie Engenharia", "Delta InfoTech", "Echo Consultoria", "Foxtrot Serviços",
    "Golf Segurança", "Hotel Consultoria", "India Serviços", "Juliett Tecnologia", "Kilo Inovações", "Lima Sistemas",
    "Mike Consultoria", "November Construções", "Oscar InfoTech", "Papa Soluções", "Quebec Serviços", "Romeu Engenharia",
    "Sierra Soluções", "Tango Segurança"]