job_titles = [
    "Analista de Marketing Digital",
    "Desenvolvedor Front-end",
    "Engenheiro de Software",
    "Gerente de Projetos",
    "Arquiteto de Soluções",
    "Especialista em SEO",
    "Consultor de Vendas",
    "Analista de Dados",
    "Cientista de Dados",
    "Desenvolvedor Back-end",
    "Designer Gráfico",
    "Gerente de Contas",
    "Analista de RH",
    "Coordenador de TI",
    "Analista Financeiro",
    "Gerente de Operações",
    "Técnico de Suporte",
    "Engenheiro de DevOps",
    "Desenvolvedor Mobile",
    "Analista de Segurança da Informação",
    "Especialista em Redes",
    "Gerente de Produto",
    "Analista de Business Intelligence",
    "Consultor de Marketing",
    "Especialista em Cloud",
    "Engenheiro de Dados",
    "Analista de Sistemas",
    "Desenvolvedor Full Stack",
    "Analista de Suporte Técnico",
    "Coordenador de Projetos",
    "Analista de Qualidade",
    "Engenheiro de Testes",
    "Especialista em Infraestrutura",
    "Designer UX/UI",
    "Arquiteto de Software",
    "Consultor de Negócios",
    "Analista de Comunicação",
    "Gerente de Recursos Humanos",
    "Coordenador de Logística",
    "Analista de Compras",
    "Desenvolvedor de Jogos",
    "Analista de Marketing de Conteúdo",
    "Especialista em E-commerce",
    "Consultor de TI",
    "Analista de CRM",
    "Gerente de Desenvolvimento",
    "Analista de Processos",
    "Engenheiro de Redes",
    "Desenvolvedor Python",
    "Analista de Performance",
    "Consultor de Segurança da Informação",
    "Coordenador de Atendimento",
    "Analista de Trade Marketing",
    "Gerente de TI",
    "Desenvolvedor Java",
    "Especialista em Inteligência Artificial",
    "Analista de Logística",
    "Designer de Produto",
    "Consultor de RH",
    "Gerente de Marketing",
    "Analista de Mídias Sociais",
    "Engenheiro de Software Sênior",
    "Analista de Projetos",
    "Desenvolvedor PHP",
    "Especialista em Machine Learning",
    "Consultor de Negócios Digitais",
    "Gerente de Segurança da Informação",
    "Analista de Infraestrutura",
    "Engenheiro de Sistemas",
    "Desenvolvedor C++",
    "Analista de Produção",
    "Consultor de Comunicação",
    "Coordenador de Suporte Técnico",
    "Analista de Pricing",
    "Desenvolvedor Ruby",
    "Especialista em Automação",
    "Consultor de Cloud",
    "Gerente de Vendas",
    "Analista de E-commerce",
    "Engenheiro de Computação",
    "Desenvolvedor .NET",
    "Analista de Riscos",
    "Consultor de Gestão",
    "Coordenador de Qualidade",
    "Analista de Testes",
    "Desenvolvedor de Aplicativos",
    "Especialista em Transformação Digital",
    "Consultor de Performance",
    "Gerente de Projetos Ágeis",
    "Analista de Segurança",
    "Engenheiro de Aplicações",
    "Desenvolvedor React",
    "Analista de BI",
    "Consultor de Desenvolvimento",
    "Coordenador de Desenvolvimento",
    "Analista de Negócios",
    "Desenvolvedor Node.js",
    "Especialista em IoT",
    "Consultor de Inovação",
    "Gerente de Serviços",
    "Analista de Controle de Qualidade",
    "Engenheiro de Infraestrutura",
    "Desenvolvedor Angular",
    "Analista de TI",
    "Consultor de Projetos",
    "Coordenador de Infraestrutura",
    "Analista de Implementação",
    "Desenvolvedor SQL",
    "Especialista em Sistemas",
    "Consultor de Tecnologia",
    "Gerente de Implementação",
    "Analista de Governança",
    "Engenheiro de Automação",
    "Desenvolvedor iOS",
    "Analista de Contabilidade",
    "Consultor de Serviços",
    "Coordenador de Desenvolvimento de Software",
    "Analista de Relacionamento",
    "Desenvolvedor Android",
    "Especialista em Big Data",
    "Consultor de Infraestrutura",
    "Gerente de Arquitetura",
    "Analista de Processos de Negócios",
    "Engenheiro de Produção",
    "Desenvolvedor Salesforce",
    "Analista de Negócios Digitais",
    "Consultor de BI",
    "Coordenador de Segurança da Informação",
    "Analista de Configuração",
    "Desenvolvedor JavaScript",
    "Especialista em UX",
    "Consultor de Arquitetura de TI",
    "Gerente de Integração",
    "Analista de Sustentabilidade",
    "Engenheiro de Qualidade",
    "Desenvolvedor Web",
    "Analista de Pesquisa de Mercado",
    "Consultor de Vendas Técnicas",
    "Coordenador de CRM",
    "Analista de Documentação",
    "Desenvolvedor de APIs",
    "Especialista em Virtualização",
    "Consultor de Treinamento",
    "Gerente de Desenvolvimento de Sistemas",
    "Analista de Recursos Humanos",
    "Engenheiro de Field Service",
    "Desenvolvedor de Banco de Dados",
    "Analista de Supply Chain",
    "Consultor de Processos",
    "Coordenador de Melhoria Contínua",
    "Analista de Contratos",
    "Desenvolvedor de Blockchain",
    "Especialista em Processos",
    "Consultor de Estratégia",
    "Gerente de Planejamento",
    "Analista de Suporte ao Cliente",
    "Engenheiro de Suporte",
    "Desenvolvedor de Chatbots",
    "Analista de Transformação Digital",
    "Consultor de Otimização",
    "Coordenador de Suporte ao Cliente",
    "Analista de Indicadores",
    "Desenvolvedor de Microserviços",
    "Especialista em Arquitetura de Software",
    "Consultor de Qualidade",
    "Gerente de Mobilidade",
    "Analista de Prospecção de Clientes",
    "Engenheiro de Energia",
    "Desenvolvedor de Sistemas Embarcados",
    "Analista de Gestão de Projetos",
    "Consultor de Engenharia de Software",
    "Coordenador de Compliance",
    "Analista de Cadastro",
    "Desenvolvedor de Realidade Aumentada",
    "Especialista em Gestão de Projetos",
    "Consultor de Operações",
    "Gerente de Tecnologia da Informação",
    "Analista de Integração de Sistemas",
    "Engenheiro de Segurança",
    "Desenvolvedor de Realidade Virtual",
    "Analista de P&D",
    "Consultor de Gestão de Mudanças",
    "Coordenador de Inovação",
    "Analista de Suporte a Sistemas",
    "Desenvolvedor de Softwares Corporativos",
    "Especialista em Gestão de Pessoas",
    "Consultor de Processos Industriais",
    "Gerente de Cibersegurança",
    "Analista de TI Pleno",
    "Engenheiro de Telecomunicações",
    "Desenvolvedor de Sistemas Corporativos",
    "Analista de Mobilidade",
    "Consultor de Automação de Processos",
    "Coordenador de Segurança de Redes",
    "Analista de Operações",
    "Desenvolvedor de Softwares de Segurança",
    "Especialista em Gestão de TI",
    "Consultor de Arquitetura Corporativa",
    "Gerente de Infraestrutura de TI",
    "Analista de Tecnologia",
    "Engenheiro de Integração",
    "Desenvolvedor de Aplicações de Segurança",
    "Analista de Desenvolvimento de Sistemas",
    "Consultor de Engenharia de Dados",
    "Coordenador de Projetos de TI",
    "Analista de Sistemas Sênior",
    "Desenvolvedor de Sistemas IoT",
    "Especialista em Desenvolvimento de Software",
    "Consultor de Gestão de Riscos",
    "Gerente de Desenvolvimento de Produtos",
    "Analista de Negócios de TI",
    "Engenheiro de Controle de Qualidade",
    "Desenvolvedor de Aplicações Corporativas",
    "Analista de Soluções Digitais",
    "Consultor de Desenvolvimento de Sistemas",
    "Coordenador de Desenvolvimento de Produtos",
    "Analista de Inteligência de Mercado",
    "Desenvolvedor de Aplicações Web",
    "Especialista em Automação de Testes",
    "Consultor de Gestão Empresarial",
    "Gerente de Soluções Tecnológicas"
]