CREATE SCHEMA IF NOT EXISTS pii;
CREATE ROLE consumer WITH LOGIN PASSWORD 'password';
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO consumer;
-- REVOKE ALL PRIVILEGES ON TABLE pessoa FROM consumer;
